name: CI for React App

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN2 }}

      - name: Build and push Docker image
        run: |
          docker build --build-arg REACT_APP_GITHUB_TOKEN=${{ secrets.REACT_APP_GITHUB_TOKEN }} -t ghcr.io/data-anonymization-tool/data-anonymization-ui:latest .
          docker push ghcr.io/data-anonymization-tool/data-anonymization-ui:latest
